### ISSUE TITLE
how can I track mouse and keyboard action in electron version . 13.0

### ISSUE THREAD

**Issue by 8KCool** [BlackPandalancer/Employee-tracking-frontend-Electron#4]
In electron version 11.0, for tracking mouse and keyboard I used iohook module .
But with high version, I can not use this module.

**Comment by brilliantseniordev** [comment]
Maybe it is related to version

**Comment by 8KCool** [comment]
> 

right...
I have solved it now... 
It is related to version.
To solve it I use node version 14.17.5 and electron version 11.0.0

**Comment by brilliantseniordev** [comment]
Great
